env:
  global:
    - BUILD_VERSION=0.1.$TRAVIS_BUILD_NUMBER
    - secure: s7nrzOj9MYCH8weiKVG1wR1h+DoBAia28BE2KSlagkAZTX4qPKu/Mfr3QJv4N7LxP1FX5GngN78XavGJvjJhEoss8FG4z6THff4Ghiza6usT4TCMmT3MJ469ejKuKkAzGqBvQ9+YYXg01zqd2OD2XxOwyPXtmhQ+JbYojo0E1eYoEvdpk/Y5zPMs++0kzFsIUJkHuo60teZGonLI83xG8uInGDQ2ZqR65/1wC2irojxeCVlRU3ZDCoHoTcSPgVjOpafrKj50C2+SkqnySr+GX3a9hYIXyrwDph95eAiWK28fnPhIvmax0mbbwsaEEwORXlSA1vgr4WyGD9VPV1f2KPBJ/HbJiMieG2AIP9wu+OBSAtZYVQd4eF0buCVe6/MxGuAIPAdCNBMiGEjVJbCuZU5knBswofH50RZGlIaZpqHonYMUH0c/+YpXVfK257KAYANx/NdSPAd25HcDrmpIc7EZ4BQsG3Z0MADEUsucv73Z5jqOqPv8b2fryTYMx9kaJHq6ur0tTivd4CHblItETDoGsXEiOdVHgTxJ7to7/gBZ1061DX/Pn+Fux/kD2MWhunbchIHBpUe4QrFKAzvnvZ4AfNFwmiXFkf4pBEFml/GGjPsTVT0UIRPD9KUpd5yNoK8dR3f6AxtGL5mqI/XsyCwiBMV3v4DVyh7V2+S2rkg=
sudo: false
services:
  - docker
before_install:
  - make build VERSION=$BUILD_VERSION
script:
  - make test VERSION=$BUILD_VERSION
after_success:
  - make tag VERSION=$BUILD_VERSION GH_TOKEN=$BUILD_KEY
